# Numpy

In [1]:
import numpy as np

## ndarray

In [2]:
a = np.array([0,1,2])
b = np.array([1,2,'3']) # 같은 종류의 데이터만 담을 수 있다.
a, b

(array([0, 1, 2]), array(['1', '2', '3'], dtype='<U11'))

In [3]:
d = np.array([[1,2,3],
             [4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array1 = np.arange(4)
array1

array([0, 1, 2, 3])

In [5]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
print(a.shape) # n행 m열
print(a.ndim) # 차원(축)의 개수
print(a.dtype.name) # 데이터타입
print(a.itemsize) # 배열의 각 요소의 바이트에서의 사이즈: float64 형식의 요소의 배열은 itemsize 8(64/8), complex32면 itemsize 4
print(a.size) # 전체 요소들의 갯수
print(type(a)) # array type

(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>


In [7]:
b = np.array([6, 7, 8])
print(b)
type(b)

[6 7 8]


numpy.ndarray

In [8]:
# 0으로 초기화 및 float 타입 지정
array2 = np.zeros((4,4), dtype=float)
array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# 1로 초기화 및 문자열 타입 지정
array3 = np.ones((3,3), dtype=str)
array3

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [10]:
# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3,3))
array4

array([[4, 1, 8],
       [8, 5, 9],
       [5, 6, 3]])

In [11]:
# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3,3))
array5

array([[-0.87618615, -0.08548636,  0.51572867],
       [ 0.07839647,  1.64581608, -0.35429743],
       [-0.42710936,  0.03933492,  0.66003289]])

## 배열 합치기
> np.concatenate

In [12]:
# concatenate
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
array3

(6,)


array([1, 2, 3, 4, 5, 6])

## 배열 형태 바꾸기
> np.reshape

- numpy array의 reshape는 기존 데이터는 유지하고 차원과 형상을 바꿔준다. (-1로 설정하면 나머지를 자동으로 맞춰준다.)
  - (100,) -> (2,50) : 변환가능
  - (100,) -> (2, -1) : 1차원은 2로 지정하고 2차원은 자동이므로 50이 됨
- 바꾸는 개수가 나눠지지 않는다면 "ValueError: cannot reshape array of size" 에러 발생
  - (100,) -> (3, -1) : 100은 3으로 나눠지지 않기때문에 에러 발생

In [13]:
a = np.arange(100).reshape(3, -1)
a

ValueError: cannot reshape array of size 100 into shape (3,newaxis)

In [ ]:
a = np.arange(15).reshape(3, 5)
a

In [ ]:
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
array2

## 배열 세로 축으로 합치기

In [ ]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
array2

In [ ]:
array3 = np.concatenate([array1, array2], axis=0)
array3

## 배열 나누기

In [ ]:
array = np.arange(10).reshape(2,5)
left, right = np.split(array, [2], axis=1)
print(array)
print(left.shape)
print(left)
print(right.shape)
print(right)

## 상수 연산

In [ ]:
array = np.random.randint(1, 10, size=4).reshape(2,2)
array

In [ ]:
result_array = array*10
result_array

## 서로 다른 형태의 Numpy 연산(Broadcasting)

In [ ]:
array1 = np.arange(4).reshape(2,2) # (2x2)
array2 = np.arange(2) # (1x2)
array3 = array1 + array2
print(array1)
print(array2)
array3

In [ ]:
x = np.array([1,2,3]).reshape(3,1)
y = np.array([4,5,6,7]).reshape(1,4)
x, y

In [ ]:
z = x + y
print(z.shape)
z
# z is 3x4 dimensional.

In [ ]:
array1 = np.arange(0, 8).reshape(2,4)
array2 = np.arange(0, 8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis=0)
array3

In [ ]:
array4 = np.arange(0,4).reshape(4,1)
array4

In [ ]:
array3 + array4
# array 3 + 
# array4
# 0 0 0 0    
# 1 1 1 1 
# 2 2 2 2
# 3 3 3 3

### 3차원

In [ ]:
array1 = np.arange(6)
array2 = array1.reshape(2,3,1)
array1, array2

In [ ]:
array3 = np.arange(8)
array4 = array3.reshape(2,1,4)
x = array2 + array4
x.shape, x

## 마스킹연산

In [ ]:
array1 = np.arange(16).reshape(4,4)
array1

In [ ]:
array2 = array1 < 10
array2

In [ ]:
array1[array2] = 100
array1 # True로 체크된 원소들 모두 100으로 변경

## 집계함수

In [ ]:
array = np.arange(16).reshape(4,4)
print("최대값: ", np.max(array))
print("최솟값: ", np.min(array))
print("합계: ", np.sum(array))
print("평균값: ", np.mean(array))

In [ ]:
array

In [ ]:
print("col합계: ", np.sum(array, axis=0))
print("row합계: ", np.sum(array, axis=1))

## Numpy의 저장과 불러오기

In [ ]:
# 단일 객체 저장 및 불러오기 save
array = np.arange(0, 10)
np.save('saved.npy', array)

In [ ]:
result = np.load('saved.npy')
result

In [ ]:
# 복수 객체 저장 및 불러오기 savez
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

In [ ]:
data = np.load('saved.npz')
data

In [ ]:
result1 = data['array1']
result2 = data['array2']
result1, result2

## 원소의 정렬

In [ ]:
# 오름차순 정렬
array = np.array([5,9,10,3,1])
array

In [ ]:
array.sort()
array

In [ ]:
# 내림차순
array[::-1]

In [ ]:
# 각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1], [8,3,4,2,5]])
array

In [ ]:
array.sort(axis=0)
array

In [ ]:
# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5) # 0부터 10사이를 5개의 데이터로 채운다
array

In [ ]:
# 난수의 재연 (실행마다 결과 동일)
np.random.seed(7) # seed 설정해주면 동일
np.random.randint(0, 10, (2,3))

In [ ]:
# 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
array2[0] = 99
array1, array2

In [ ]:
# 중복된 원소 제거
array = np.array([1,1,2,2,3,3,4,5])
unique_array = np.unique(array)
array, unique_array

In [ ]:
a = np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])
np.sort(a, axis=1)

In [ ]:
# argsort : 정렬된 순서만 알고 싶을때 사용
a = np.array([[4,3,5,7],
             [1,12,11,9],
             [2,15,1,14]])
np.argsort(a, axis=1)